// <auto-generated />
using System;
using DataBanGiay.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBanGiay.Migrations
{
    [DbContext(typeof(BanGiayDBConText))]
    [Migration("20230523020243_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataBanGiay.Model.ChatLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ChatLieus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenChatLieu = "Da",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenChatLieu = "Vải",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenChatLieu = "Giả da",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.ChucVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChucVu", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenCV = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            TenCV = "Nhân Viên"
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.GioHang", b =>
                {
                    b.Property<int>("IdNV")
                        .HasColumnType("int");

                    b.HasKey("IdNV");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("DataBanGiay.Model.GioHangChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("IdNV")
                        .HasColumnType("int");

                    b.Property<int>("IdSPCT")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNV");

                    b.HasIndex("IdSPCT");

                    b.ToTable("GioHangCT", (string)null);
                });

            modelBuilder.Entity("DataBanGiay.Model.HangGiay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HangGiay", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenHang = "Sneaker",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenHang = "Adidas",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenHang = "Nike",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            TenHang = "Converse",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 5,
                            TenHang = "Puma",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdKH")
                        .HasColumnType("int");

                    b.Property<int>("IdNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdKH");

                    b.HasIndex("IdNV");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("DataBanGiay.Model.HoaDonChiTiet", b =>
                {
                    b.Property<int>("IdSPCT")
                        .HasColumnType("int");

                    b.Property<int>("IdHD")
                        .HasColumnType("int");

                    b.Property<string>("AnhSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdSPCT", "IdHD");

                    b.HasIndex("IdHD");

                    b.ToTable("HoaDonCT", (string)null);
                });

            modelBuilder.Entity("DataBanGiay.Model.KhachHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("gioitinh")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KhachHang", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Hà Nội",
                            Diem = 1000,
                            HovaTen = "Chuyên Săn Sale",
                            MatKhau = "123456",
                            NgaySinh = new DateTime(2023, 5, 23, 9, 2, 42, 870, DateTimeKind.Local).AddTicks(1932),
                            SDT = "0123456788",
                            TaiKhoan = "KhachHang01",
                            gioitinh = false
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.MauSac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("MauSac", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenMau = "Đen",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenMau = "Trắng",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenMau = "Đen Trắn",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            TenMau = "Nâu",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCV")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdCV");

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiaChi = "Hà Nội",
                            GioiTinh = false,
                            HovaTen = "Ngô Quốc Mạnh",
                            IdCV = 1,
                            MatKhau = "123456",
                            NgaySinh = new DateTime(2023, 5, 23, 9, 2, 42, 870, DateTimeKind.Local).AddTicks(1721),
                            SDT = "0336253482",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            DiaChi = "Hà Nội",
                            GioiTinh = false,
                            HovaTen = "Trần Quốc Toản",
                            IdCV = 2,
                            MatKhau = "123456",
                            NgaySinh = new DateTime(2023, 5, 23, 9, 2, 42, 870, DateTimeKind.Local).AddTicks(1745),
                            SDT = "0123456789",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SanPham", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenSP = "Giày Jordan Cổ Cao",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            TenSP = "Giày tây nam Derby GNLA9636-119-D",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            TenSP = "Giày Cao Gót GU2427",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            TenSP = "Giày Thể Thao Sneaker",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.SanPhamChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnhSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("IDLoai")
                        .HasColumnType("int");

                    b.Property<int>("IdChatLieu")
                        .HasColumnType("int");

                    b.Property<int>("IdHang")
                        .HasColumnType("int");

                    b.Property<int>("IdMauSac")
                        .HasColumnType("int");

                    b.Property<int>("IdSP")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IDLoai");

                    b.HasIndex("IdChatLieu");

                    b.HasIndex("IdHang");

                    b.HasIndex("IdMauSac");

                    b.HasIndex("IdSP");

                    b.ToTable("SanPhamCT", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnhSP = "https://streetstyleshop.vn/wp-content/uploads/2020/12/giay-cao-got-di-tiec-8-1.jpg",
                            DonGia = 600000,
                            IDLoai = 2,
                            IdChatLieu = 1,
                            IdHang = 1,
                            IdMauSac = 2,
                            IdSP = 3,
                            Size = 39,
                            SoLuongTon = 20
                        },
                        new
                        {
                            Id = 2,
                            AnhSP = "https://product.hstatic.net/200000641225/product/0f0a5211_383ec08839f34720afb1578c08f5df80_master.jpg",
                            DonGia = 500000,
                            IDLoai = 3,
                            IdChatLieu = 2,
                            IdHang = 1,
                            IdMauSac = 3,
                            IdSP = 4,
                            Size = 37,
                            SoLuongTon = 20
                        },
                        new
                        {
                            Id = 3,
                            AnhSP = "https://streetstyleshop.vn/wp-content/uploads/2020/12/giay-cao-got-di-tiec-8-1.jpg",
                            DonGia = 600000,
                            IDLoai = 2,
                            IdChatLieu = 1,
                            IdHang = 1,
                            IdMauSac = 2,
                            IdSP = 3,
                            Size = 32,
                            SoLuongTon = 20
                        },
                        new
                        {
                            Id = 4,
                            AnhSP = "https://laforce.vn/wp-content/uploads/2018/12/giay-tay-nam-cong-so-basic-gnla9636-119-d-1-4.jpg",
                            DonGia = 1800000,
                            IDLoai = 4,
                            IdChatLieu = 1,
                            IdHang = 1,
                            IdMauSac = 1,
                            IdSP = 2,
                            Size = 38,
                            SoLuongTon = 20
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.TheLoai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LoaiGiay")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TheLoai", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoaiGiay = "Giày Thể Thao",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 2,
                            LoaiGiay = "Giày Cao Gót",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 3,
                            LoaiGiay = "Giày sneaker",
                            TrangThai = true
                        },
                        new
                        {
                            Id = 4,
                            LoaiGiay = "Giày Tây",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DataBanGiay.Model.GioHang", b =>
                {
                    b.HasOne("DataBanGiay.Model.NhanVien", "NhanViens")
                        .WithMany("GioHangs")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DataBanGiay.Model.GioHangChiTiet", b =>
                {
                    b.HasOne("DataBanGiay.Model.GioHang", "gioHangs")
                        .WithMany("GioHangChiTiets")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.SanPhamChiTiet", "sanPhamChiTiets")
                        .WithMany("gioHangChiTiets")
                        .HasForeignKey("IdSPCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("gioHangs");

                    b.Navigation("sanPhamChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.HoaDon", b =>
                {
                    b.HasOne("DataBanGiay.Model.KhachHang", "khachHangs")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.NhanVien", "nhanViens")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("khachHangs");

                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("DataBanGiay.Model.HoaDonChiTiet", b =>
                {
                    b.HasOne("DataBanGiay.Model.HoaDon", "hoaDons")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("IdHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.SanPhamChiTiet", "sanPhamChiTiets")
                        .WithMany("hoaDonChiTiets")
                        .HasForeignKey("IdSPCT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoaDons");

                    b.Navigation("sanPhamChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.NhanVien", b =>
                {
                    b.HasOne("DataBanGiay.Model.ChucVu", "chucVus")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdCV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chucVus");
                });

            modelBuilder.Entity("DataBanGiay.Model.SanPhamChiTiet", b =>
                {
                    b.HasOne("DataBanGiay.Model.TheLoai", "theLoais")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IDLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.ChatLieu", "chatLieus")
                        .WithMany("sanPhamChiTiets")
                        .HasForeignKey("IdChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.HangGiay", "hangGiays")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.MauSac", "mauSacs")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdMauSac")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBanGiay.Model.SanPham", "sanPhams")
                        .WithMany("SanPhamChiTiets")
                        .HasForeignKey("IdSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chatLieus");

                    b.Navigation("hangGiays");

                    b.Navigation("mauSacs");

                    b.Navigation("sanPhams");

                    b.Navigation("theLoais");
                });

            modelBuilder.Entity("DataBanGiay.Model.ChatLieu", b =>
                {
                    b.Navigation("sanPhamChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("DataBanGiay.Model.GioHang", b =>
                {
                    b.Navigation("GioHangChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.HangGiay", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.HoaDon", b =>
                {
                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DataBanGiay.Model.MauSac", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.NhanVien", b =>
                {
                    b.Navigation("GioHangs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DataBanGiay.Model.SanPham", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.SanPhamChiTiet", b =>
                {
                    b.Navigation("gioHangChiTiets");

                    b.Navigation("hoaDonChiTiets");
                });

            modelBuilder.Entity("DataBanGiay.Model.TheLoai", b =>
                {
                    b.Navigation("SanPhamChiTiets");
                });
#pragma warning restore 612, 618
        }
    }
}
